import { Poppins } from "next/font/google";
import "../style/globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Tripbookngo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased bg-background text-foreground leading-relaxed",
          poppins.className
        )}
      >
        <Navbar />
        <main className="pt-20">{children}</main>
        <Toaster position="bottom-right" reverseOrder={false} />
        <Footer />
      </body>
    </html>
  );
}
